title: Pretty Printed JSON
description: JSON body string is not a pretty printed JSON but in one line.
target:
  - Response_Body
  - Request_Body
error: JSON is not pretty-printed, expecting one key per line.


