const webpack = require('webpack');
const path = require('path');
const _ = require('lodash');
const fs = require('fs');

const helpers = require('./helpers');
const template = require('./templates');

const rules = helpers.getRules();

const webpackConfig = {
  entry: [],
  output: {
    path: path.resolve(__dirname, '../build/'),
    filename: 'functions.js',
    library: 'functions',
    // libraryTarget: 'commonjs2'
    // libraryExport: 'validatePrettyPrintedJson_webpack',
    // libraryTarget: 'var',
  },
  target: 'node',
  mode: 'production',
  cache: true,
  optimization: {
    minimize: false,
  },
};

function getEntry(inRules) {
  const basePath = path.resolve(__dirname, '../');

  let entryFile = '';
  let exports = '';

  _.each(inRules, (rule) => {
    entryFile += `const ${rule.rule.functionName}_webpack = require('./${rule.functionsFile}').${rule.rule.functionName};\n`;
    exports += `  ${rule.rule.functionName}_webpack,\n`;
  });

  entryFile += `\nmodule.exports = {\n${exports}};\n`;

  const entryPath = path.join(basePath, 'entry.js');

  fs.writeFileSync(entryPath, entryFile);

  return entryPath;
}

_.each(rules.rules, (rule) => {
  fs.writeFileSync(`${rule.ruleDir}README.md`, template.generateRule(rule));
});

function getFunction(rule) {
  const fcTemplate = `/*
<%= title %>
<%= intent %>

@targets: <%= allowedTargets %>
@minim: <%= minim %>
*/
function <%= fName %>(data) {
  return functions.<%= fName %>_webpack(data);
}
`;

  return _.template(fcTemplate)({
    title: rule.title,
    intent: rule.intent,
    allowedTargets: (rule.allowedTargets || []).join(', '),
    minim: `${!!rule.minim}`,
    fName: rule.functionName,
  });
}

function generateFunctions(wpConfig, inRules, cb) {
  const functionsFile = `${wpConfig.output.path}/${wpConfig.output.filename}`;

  if (fs.existsSync(functionsFile)) {
    fs.unlinkSync(functionsFile);
  }

  webpack(wpConfig, (err) => {
    if (err) {
      return cb(err);
    }

    let fctions = '';
    let generated = fs.readFileSync(functionsFile, 'utf8');

    _.each(inRules, (rule) => {
      fctions += `${getFunction(rule.rule)}\n`;
    });

    generated = `
${fctions}
/**************************************************************/
/****Generated by WEBPACK**************************************/
/**************************************************************/
${generated}`;

    fs.writeFileSync(functionsFile, generated);

    return cb();
  });
}

fs.writeFileSync(`${path.resolve(__dirname, '../build')}/README.md`, template.generateStyleguide(rules));

const entry = getEntry(rules.rules);

webpackConfig.entry = entry;

generateFunctions(webpackConfig, rules.rules, (err) => {
  if (err) {
    console.error(err);
  }

  fs.unlinkSync(entry);
});
