#!/bin/bash
# Generate rules file for each styleguide based on enabled_rules
# Generate good examples file for each rule
# Generate bad examples file for each rule
# Transclude every styleguide in ./styleguides


BASE_DIR=.
STYLEGUIDES_DIR=$BASE_DIR/styleguides
RULES_DIR=$BASE_DIR/rules

RULES_FILENAME=Rules-generated.md
GOOD_EXAMPLES_FILENAME=GoodExamples-generated.md
BAD_EXAMPLES_FILENAME=BadExamples-generated.md

STYLEGUIDE_FILE=StyleGuide
RULE_FILE=Rule
GOODEXAMPLES_FILE=GoodExample
BADEXAMPLES_FILE=BadExample
README_FILE=README.md
TEMPLATE_DIR=./scripts/templates

# For every rule in the RULES_DIR
for rule in \
  `find $RULES_DIR -type d -depth 1 | tr / ' ' | awk '{print $NF}'` \
; do

  echo "Processing rule '$rule'"

  # Copy rule template
  cp $TEMPLATE_DIR/$RULE_FILE.md $RULES_DIR/$rule/$RULE_FILE-generated.md

  # Generate Good Examples File
  good_examples_path=$RULES_DIR/$rule/good-examples/
  good_examples_file=$good_examples_path/$GOOD_EXAMPLES_FILENAME
  > $good_examples_file

  # For each good example
  for example_dir in \
    `find $good_examples_path -type d -depth 1 | tr / ' ' | awk '{print $NF}'` \
  ; do

    # Add it to template
    echo ":[$example_dir](./$example_dir/GoodExample-generated.md)" >> $good_examples_file
    echo "  Adding good example '$example_dir' for rule '$rule'"

    # Copy Good Example tesmlpate
    cp $TEMPLATE_DIR/$GOODEXAMPLES_FILE.md \
      $good_examples_path/$example_dir/$GOODEXAMPLES_FILE-generated.md

    # Transclude Example Readme
    echo "    Transcluding example Readme '$good_examples_path/$example_dir/$README_FILE'"
    hercule $good_examples_path/$example_dir/$GOODEXAMPLES_FILE-generated.md \
      -o $good_examples_path/$example_dir/$README_FILE

  done

  # Generate Bad Examples File
  bad_examples_path=$RULES_DIR/$rule/bad-examples/
  bad_examples_file=$bad_examples_path/$BAD_EXAMPLES_FILENAME
  > $bad_examples_file

  # For each bad example
  for example_dir in \
    `find $bad_examples_path -type d -depth 1 | tr / ' ' | awk '{print $NF}'` \
  ; do

    # Add it to template
    echo ":[$example_dir](./$example_dir/BadExample-generated.md)" >> $bad_examples_file
    echo "  Adding bad example '$example_dir' for rule '$rule'"

    # Copy Bad Example temlpate
    cp $TEMPLATE_DIR/$BADEXAMPLES_FILE.md \
      $bad_examples_path/$example_dir/$BADEXAMPLES_FILE-generated.md


    # Transclude Example Readme
    echo "    Transcluding example Readme '$bad_examples_path/$example_dir/$README_FILE'"
    hercule $bad_examples_path/$example_dir/$BADEXAMPLES_FILE-generated.md \
      -o $bad_examples_path/$example_dir/$README_FILE
  done

  # Transclude Rule Readme
  echo "  Transcluding rule Readme '$RULES_DIR/$rule/$README_FILE'"
  hercule $RULES_DIR/$rule/$RULE_FILE-generated.md \
    -o $RULES_DIR/$rule/$README_FILE
done

# Generate rules file for each styleguide based on enabled_rules
for styleguide in \
  `find $STYLEGUIDES_DIR -type d -depth 1 | tr / ' ' | awk '{print $NF}'` \
; do

  echo "Processing styleguide '$styleguide'"

  styleguide_dir=$STYLEGUIDES_DIR/$styleguide

  # Create the rule file
  rulefile_path=$styleguide_dir/$RULES_FILENAME-generated
   > $rulefile_path

  for enabled_rule in `cat $styleguide_dir/enabled_rules`; do
    # Test the presence in the rule dir and explode in case it's not found
    rule_dir=$RULES_DIR/$enabled_rule

    if [ ! -d "$rule_dir" ]; then
      # Explode if the rule in enabled rules isn't a rule in the ruledir
      echo "Error: The rule dir '$enabled_rule' in '$styleguide_dir/enabled_rules'" \
           "not found in the rules directory '$RULES_DIR' "
      # Cleanup generated and template Markdowns
      find . | grep "generated.md" | xargs rm

      exit 1
    fi

    rulefile_path=$styleguide_dir/$RULES_FILENAME
    echo ":[$enabled_rule](../../rules/$enabled_rule/Rule-generated.md)" >> $rulefile_path
    echo "  Adding rule '$enabled_rule'"
  done

  # Copy Style Guide template
  cp $TEMPLATE_DIR/$STYLEGUIDE_FILE.md $styleguide_dir/$STYLEGUIDE_FILE-generated.md

  # Transclude all the markdowns
  transcluded_path=$STYLEGUIDES_DIR/$styleguide/$README_FILE
  echo "  Transcluding Style Guide Readme to '$transcluded_path'"
  hercule $styleguide_dir/$STYLEGUIDE_FILE-generated.md -o $transcluded_path

  # Cleanup generated and template Markdowns
  find . | grep "generated.md" | xargs rm
done
