title: Not dash lowercased
description: Literal parts of the URI templates are not dash lowercased
error: Uri part "/test-Not-LoweRcased/" is not lowercased or dash separated.
target: Resource_URI_Template
